import pandas as pd
import matplotlib.pyplot as plt

# Read the results generated by the C++ C(ii) experiment
df = pd.read_csv("cii_results.csv")


# =========================================================
# GRAPH 1: KEY COMPARISONS VS THRESHOLD S
# =========================================================

plt.figure(figsize=(10, 6))

plt.plot(
    df["S"],
    df["Key Comparisons"],
    marker="o",
    markersize=4
)

plt.xlabel("Threshold Values S")
plt.ylabel("Number of Key Comparisons")
plt.title(
    "Number of Key Comparisons over Different Threshold Values S"
)

plt.grid(True)
plt.tight_layout()

plt.savefig(
    "cii_key_comparisons.png",
    dpi=300
)

plt.show()


# =========================================================
# GRAPH 2: CPU TIME VS THRESHOLD S
# =========================================================

plt.figure(figsize=(10, 6))

plt.plot(
    df["S"],
    df["CPU Time (ms)"],
    marker="o",
    markersize=4
)

plt.xlabel("Threshold Values S")
plt.ylabel("CPU Time (ms)")
plt.title(
    "CPU Time over Different Threshold Values S"
)

plt.grid(True)
plt.tight_layout()

plt.savefig(
    "cii_cpu_time.png",
    dpi=300
)

plt.show()
